### ISSUE TITLE
Repostitory structure for master is not compliant

### ISSUE THREAD

**Issue by mbrygert** [mKeRix/hassio-repo#8]
Getting "Repostitory structure for master is not compliant" erros when trying to add customer repo on HACS
HACS:
Integration version: | 1.3.3
Frontend version: | 202008050145

HomeAssistant version 0.114.1 supervised on Raspberry Pi 4

**Comment by mKeRix** [comment]
This repository is not for HACS, it's for the Home Assistant add-ons section. Check the docs for how to add to this here: https://www.home-assistant.io/hassio/installing_third_party_addons/

Note that you only need this if you want to run room-assistant and track something from the same machine that your supervised Home Assistant is running on. Otherwise there is nothing special needed, room-assistant works with the native MQTT integration.
